[package]
	authors = { workspace = true }
	edition = { workspace = true }
	license = { workspace = true }
	name    = "nand7400"
	version = { workspace = true }

	# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
	# Parsing 
	pest        = "~2"                                      # Parsing source code
	pest_derive = "~2"                                      # Parsing source code
	serde       = { version = "~1", features = ["derive"] } # De/serialization

	# Error handling
	miette = "~5"   # For pretty errors.
	snafu  = "~0.7" # For error handling.

	# Binding to Swift
	uniffi = { workspace = true, optional = true }

[build-dependencies]
	# Binding to Swift during buildtime.
	uniffi = { workspace = true, features = ["build"], optional = true }

[features]
	# Optionally enable binding to Swift, so we don't have to compile uniffi every time.
	uniffi = ["dep:uniffi"]

[lib]
	crate-type = ["rlib", "staticlib"]
